#!/bin/sh
# n for managing node-js versions
export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).
export XAUTHORITY=~/.Xauthority
# chruby for managing ruby versions
chruby 2.7.6
